### PR TITLE
Add data structure files week 2 courses python

### PR DESCRIPTION
**Pull request by victorronaldopasaribu**
- Tuples
- Dictionaries
- Lists

### CODE REVIEW

**Review by ariefrahmansyah — APPROVED** [review]
Awesome! LGTM! Thanks, @victorronaldopasaribu!

Btw, I have one question. Do you want to break down README.md to smaller Python files?

**Comment by victorronaldopasaribu** [comment]
> Awesome! LGTM! Thanks, @victorronaldopasaribu!
> 
> Btw, I have one question. Do you want to break down README.md to smaller Python files?

ubah ke file .py kak ?

**Comment by ariefrahmansyah** [comment]
> > Awesome! LGTM! Thanks, @victorronaldopasaribu!
> > Btw, I have one question. Do you want to break down README.md to smaller Python files?
> 
> ubah ke file .py kak ?

Iya, betul. Jadi gak perlu ada README.md, tapi file .py semua.

**Comment by victorronaldopasaribu** [comment]
> > > Awesome! LGTM! Thanks, @victorronaldopasaribu!
> > > Btw, I have one question. Do you want to break down README.md to smaller Python files?
> > 
> > 
> > ubah ke file .py kak ?
> 
> Iya, betul. Jadi gak perlu ada README.md, tapi file .py semua.

ok kak nanti saya rubah kak

**Review by ariefrahmansyah — APPROVED** [review]
Nicee, LGTM!

**Pull request merged**
